### ISSUE TITLE
Implement Triton integration with KNative Serving

### ISSUE THREAD

**Issue by NohaIhab** [canonical/knative-operators#171]
### Context

Integrate Nvidia Triton for Serving, via KServe with GPUs

### What needs to get done

set the required configurations  to deploy an ISVC with Triton and on GPU.
From #169 and #170, the configurations are:
In the `config-deployment` ConfigMap:
* `progress-deadline` set to `"600s"`
* `registries-skipping-tag-resolving` set to `"nvcr.io"`

In the `config-features` ConfigMap:
* `kubernetes.podspec-affinity: "enabled"`
* `kubernetes.podspec-nodeselector: "enabled"`
* `kubernetes.podspec-tolerations: "enabled"`

### Definition of Done

PR to enable configuring Serving in Charmed Kubeflow for Nvidia Triton is merged

**Comment by NohaIhab** [comment]
based on the spec, the implementation will be this way:
**Note:** this is the section from the spec on the chosen approach. For more details refer to spec `KF084`.

* Set the required configurations by default, so that the user does not have to change them for Triton.
* Add a config option for registries-skip-tag-resolution because it is a possible use case for users to need to add to the list. As mentioned in the point above, the default for this config will be “nvcr.io” since we know that most users would not want tag resolution on the `nvcr.io` registry. The config.yaml will be:
```
options:
  registries-skip-tag-resolution:
    default: "nvcr.io"
    description: Comma-seperated list of repositories for which tag to digest resolving should be skipped.
    type: string
```
* Add a config option for progress-deadline with a default of “600s”, this way users don’t need to change it for Triton, but also have the option to change the timeout to suit their deployments. The option in the config.yaml will be:
```
options:
  progress-deadline:
    default: "600s"
    description:  the duration to wait for the deployment to be ready before considering it failed.
    type: string
```
* Change the KnativeServing manifest to have the GPU Podspec settings enabled by default and to take in the config value both config options defined in the previous points :
```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: {{ app_name }}
  namespace: {{ serving_namespace }}
spec:
  version: {{ serving_version }}
  config:
    deployment:
      progress-deadline: {{ progress_deadline}}
      registries-skipping-tag-resolving: {{ registries_skip_tag_resolving }}
    features:
      kubernetes.podspec-affinity: "enabled"
      kubernetes.podspec-nodeselector: "enabled"
      kubernetes.podspec-tolerations: "enabled"
```
